Génération de la documentation:
javadoc paquetage  sousPaquetage -d cheminDaccesDuDocumentouRangerLaDocumentation


 La commande de compilation est :


javac -d NomdossierpourRanger -cp sourcecefichier.class - Sourcepath sourcedoc.java


Pour exécuter les test:

javac -classpath test-1.7.jar dossierOùSetrouveLefichierSource/NomClasse.java




 Pour lancer les test :
java -jar test-1.7.jar NomexecutableduTest



Creation d'archive:
extension peut être remplacé par jar ou tar par exemple:

jar cvf ../nomdArchive.extension dossierOurangerLarchive	

Visualisation de l'archive:
jar tvf nomdArchive.jar
 Extraction de l'archive d'extension tar:
jar xvf nom.jar



Compilation avec classpath afin de preciser le fichier et son aborresence:

javac -classpath test-1.7.jar test/NomDeClasseTest.java

 Execution:
java -jar test-1.7.jar NomDeClasseTest
Execution de l'Archive d'extension jar :
jar cvfm ../nomdarchive.jar ../manifest-ex dossier manifest
